#!/usr/bin/env python3
"""
Enhanced Function Plotter with Parameterized Functions
Supports the new parameterized data generator system
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import subprocess

# Available function examples with their Lean files
FUNCTION_EXAMPLES = {
    "1": {
        "name": "Quadratic Function",
        "desc": "f(x) = 3x² - 4x + 5", 
        "file": "DataGenerator.lean",
        "active_line": '#eval plotFunction quadratic "f" "3x² - 4x + 5" (-2.0) 4.0 100 [0, 1, 3]'
    },
    "2": {
        "name": "Sine Wave",
        "desc": "g(x) = sin(x)",
        "file": "DataGenerator.lean", 
        "active_line": '#eval plotFunction sine "g" "sin(x)" (-6.28) 6.28 200 [0, 1.57, 3.14, 4.71]'
    },
    "3": {
        "name": "Exponential",
        "desc": "h(x) = eˣ",
        "file": "DataGenerator.lean",
        "active_line": '#eval plotFunction exponential "h" "eˣ" (-2.0) 3.0 150 [-1, 0, 1, 2]'
    },
    "4": {
        "name": "Cubic Polynomial", 
        "desc": "p(x) = x³ - 3x² + 2x + 1",
        "file": "DataGenerator.lean",
        "active_line": '#eval plotFunction cubic "p" "x³ - 3x² + 2x + 1" (-2.0) 4.0 200 [-1, 0, 1, 2, 3]'
    },
    "5": {
        "name": "Custom x·sin(x)",
        "desc": "custom(x) = x·sin(x)",
        "file": "DataGenerator.lean",
        "active_line": '#eval plotFunction myCustomFunction "custom" "x·sin(x)" (-10.0) 10.0 300 [-3.14, 0, 3.14, 6.28]'
    },
    "6": {
        "name": "Multi-Function Demo",
        "desc": "Various parameterized functions",
        "file": "MultiFunctionExample.lean",
        "active_line": None  # Uses the file as-is
    }
}

def run_lean_data_generator(lean_file="DataGenerator.lean", custom_function_line=None):
    """Run the Lean data generator to create CSV files"""
    print(f"Generating data with Lean using {lean_file}...")
    
    # If we need to modify the active function, do it temporarily
    temp_file = None
    if custom_function_line and lean_file == "DataGenerator.lean":
        temp_file = f"{lean_file}.temp"
        modify_active_function(lean_file, temp_file, custom_function_line)
        lean_file = temp_file
    
    try:
        result = subprocess.run(['lean', lean_file], 
                              capture_output=True, text=True, check=True)
        print("✓ Lean data generation completed")
        if result.stdout.strip():
            print("Lean output:", result.stdout.strip())
        
        # Clean up temp file
        if temp_file and os.path.exists(temp_file):
            os.remove(temp_file)
            
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running Lean: {e}")
        print(f"Stderr: {e.stderr}")
        if temp_file and os.path.exists(temp_file):
            os.remove(temp_file)
        return False
    except FileNotFoundError:
        print("Error: 'lean' command not found. Please make sure Lean is installed and in PATH")
        return False

def modify_active_function(source_file, target_file, active_line):
    """Modify the Lean file to activate a specific function"""
    with open(source_file, 'r') as f:
        lines = f.readlines()
    
    with open(target_file, 'w') as f:
        in_examples_section = False
        for line in lines:
            # Comment out all existing #eval lines in the examples section
            if "-- Example" in line and "#eval" in line:
                in_examples_section = True
                f.write(f"-- {line}")
            elif line.strip().startswith('#eval plotFunction') and in_examples_section:
                f.write(f"-- {line}")
            elif "-- Example" in line and "uncomment to use" in line:
                f.write(f"-- {line}")
            elif line.strip().startswith('-- #eval plotFunction'):
                f.write(f"-- {line}")
            else:
                f.write(line)
        
        # Add the active function line at the end
        f.write(f"\n-- Active function\n{active_line}\n")

def load_data():
    """Load data from CSV files generated by Lean"""
    try:
        # Load function metadata
        metadata = {}
        if os.path.exists('function_metadata.csv'):
            with open('function_metadata.csv', 'r') as f:
                for line in f:
                    if ',' in line:
                        key, value = line.strip().split(',', 1)
                        metadata[key] = value
            print(f"✓ Loaded function metadata: {metadata.get('function_name', 'f')}(x) = {metadata.get('function_expr', 'unknown')}")
        
        # Load main plot data
        if os.path.exists('plot_data.csv'):
            plot_data = pd.read_csv('plot_data.csv')
            print(f"✓ Loaded {len(plot_data)} plot points")
        else:
            print("Warning: plot_data.csv not found, using fallback data")
            x = np.linspace(-2, 4, 50)
            plot_data = pd.DataFrame({'x': x, 'y': 3*x**2 - 4*x + 5})
            metadata = {'function_name': 'f', 'function_expr': '3x² - 4x + 5'}
        
        # Load special points
        if os.path.exists('special_points.csv'):
            special_data = pd.read_csv('special_points.csv')
            print(f"✓ Loaded {len(special_data)} special points")
        else:
            print("Warning: special_points.csv not found, using fallback points")
            special_data = pd.DataFrame({'x': [0, 1, 3], 'y': [5, 4, 20]})
        
        return plot_data, special_data, metadata
    except Exception as e:
        print(f"Error loading data: {e}")
        return None, None, {}

def create_plot(plot_data, special_data, metadata=None):
    """Create and display the plot"""
    if metadata is None:
        metadata = {}
    
    func_name = metadata.get('function_name', 'f')
    func_expr = metadata.get('function_expr', 'unknown function')
    
    plt.figure(figsize=(12, 8))
    
    # Main function curve
    plt.plot(plot_data['x'], plot_data['y'], 'b-', linewidth=2.5, 
             label=f'{func_name}(x) = {func_expr}', alpha=0.8)
    
    # Special evaluated points (only if they exist)
    if len(special_data) > 0:
        plt.scatter(special_data['x'], special_data['y'], 
                   color='red', s=80, zorder=5, 
                   label='Evaluated in Lean', edgecolors='darkred', linewidth=1.5)
    
    # Try to find and mark critical points for common function types
    try:
        # For quadratic functions, find vertex
        if 'x²' in func_expr or 'x^2' in func_expr:
            x_vals = plot_data['x'].values
            y_vals = plot_data['y'].values
            
            if len(y_vals) > 0:
                min_idx = np.argmin(y_vals)
                max_idx = np.argmax(y_vals)
                
                critical_idx = min_idx if y_vals[min_idx] < y_vals[max_idx] else max_idx
                critical_x = x_vals[critical_idx]
                critical_y = y_vals[critical_idx]
                
                critical_type = "Minimum" if critical_idx == min_idx else "Maximum"
                plt.scatter([critical_x], [critical_y], color='green', s=120, marker='*', 
                           zorder=5, label=f'{critical_type} ({critical_x:.3f}, {critical_y:.3f})',
                           edgecolors='darkgreen', linewidth=1.5)
    except Exception:
        pass  # Skip critical point detection if it fails
    
    # Styling
    plt.grid(True, alpha=0.3, linestyle='--')
    plt.xlabel('x', fontsize=12, fontweight='bold')
    plt.ylabel(f'{func_name}(x)', fontsize=12, fontweight='bold')
    plt.title(f'Parameterized Function Plot from Lean\n{func_name}(x) = {func_expr}', 
              fontsize=14, fontweight='bold', pad=20)
    
    # Annotations for special points
    for _, row in special_data.iterrows():
        plt.annotate(f'({row["x"]}, {row["y"]})', 
                    xy=(row['x'], row['y']), 
                    xytext=(10, 10), 
                    textcoords='offset points',
                    fontsize=10,
                    bbox=dict(boxstyle='round,pad=0.4', facecolor='yellow', 
                             alpha=0.8, edgecolor='orange'),
                    arrowprops=dict(arrowstyle='->', color='gray', alpha=0.7))
    
    plt.legend(fontsize=11, loc='best')
    plt.tight_layout()
    
    # Add some statistics
    print("\n📊 Function Analysis:")
    print(f"   Function: {func_name}(x) = {func_expr}")
    print(f"   Range plotted: x ∈ [{plot_data['x'].min():.1f}, {plot_data['x'].max():.1f}]")
    print(f"   Function range: y ∈ [{plot_data['y'].min():.3f}, {plot_data['y'].max():.3f}]")
    if len(special_data) > 0:
        print("   Special points evaluated:")
        for _, row in special_data.iterrows():
            print(f"     {func_name}({row['x']}) = {row['y']}")
    
    plt.show()

def show_menu():
    """Display the function selection menu"""
    print("🚀 Parameterized Function Plotter")
    print("=" * 50)
    print("Available functions:")
    for key, func in FUNCTION_EXAMPLES.items():
        print(f"  {key}. {func['name']}: {func['desc']}")
    print("  7. Custom function (edit DataGenerator.lean)")
    print()

def plot_selected_function(choice):
    """Plot the selected function"""
    if choice not in FUNCTION_EXAMPLES:
        if choice == "7":
            print("📝 Please edit DataGenerator.lean manually and run auto_plot.py")
            return True
        else:
            print(f"❌ Invalid choice: {choice}")
            return False
    
    func_info = FUNCTION_EXAMPLES[choice]
    print(f"📊 Plotting: {func_info['name']} - {func_info['desc']}")
    
    # Generate data with the selected function
    if not run_lean_data_generator(func_info['file'], func_info['active_line']):
        return False
    
    # Load and plot the data
    plot_data, special_data, metadata = load_data()
    if plot_data is None or special_data is None:
        print("❌ Failed to load data")
        return False
    
    print("\n📈 Creating plot...")
    create_plot(plot_data, special_data, metadata)
    return True

def main():
    """Main interactive function"""
    show_menu()
    
    while True:
        choice = input("Choose a function to plot (1-7, or 'q' to quit): ").strip()
        
        if choice.lower() == 'q':
            print("👋 Goodbye!")
            break
        
        if plot_selected_function(choice):
            print("\n✅ Plot generated successfully!")
            print("\n" + "="*50)
            show_menu()
        else:
            print("❌ Failed to plot function. Please try again.")

if __name__ == "__main__":
    main()